#!/usr/bin/env sh
# global settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  "Vim" "Term" "Browser" "Music" 1 2 3 4 5 6
yabai -m config status_bar_power_icon_strip
yabai -m config status_bar_space_icon
yabai -m config status_bar_clock_icon
#End Bar Config
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      exterior
yabai -m config window_border_width          1
yabai -m config window_border_radius         0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xFF52B640
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

yabai -m space 1 --label Vim
yabai -m space 2 --label Term 
yabai -m space 3 --label Browser
yabai -m space 4 --label Music

yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app=Emacs manage=on

yabai -m rule --add app=Emacs  space=^1
yabai -m rule --add app=Safari space=^3
yabai -m rule --add app=Music  space=^4
echo "yabai configuration loaded.."
